FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn -q test

RUN mvn -q clean package

FROM eclipse-temurin:17-jdk
WORKDIR /app

COPY --from=build /app/target/devcalc-api-1.0.0-jar-with-dependencies.jar app.jar

EXPOSE 7000

ENTRYPOINT ["java", "-jar", "app.jar"]
